# Based on sample workflow at https://github.com/aormsby/Fork-Sync-With-Upstream-action

name: "Sync with upstream"
on:
  schedule:
    # Run every 6 hours
    - cron: "56 */6 * * *"
    # Note: Do not add 'workflow_dispatch'. Adding it appears to make GitHub
    # ignore the 'schedule' directive.

jobs:
  sync-with-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Pull upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.1
        with:
          upstream_sync_repo: Loathing-Associates-Scripting-Society/autoscend
          upstream_sync_branch: master
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for new commits
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "New commit(s) found!"

      - name: Timestamp
        run: date

